### ISSUE TITLE
Add an issue template

### ISSUE THREAD

**Issue by Suvink** [GitHubExperts-LK/peliculopedia#2]

**Comment by nimanthadilz** [comment]
Hi, If this issue is still open, I would like to contribute. Please assign me to this issue, so others won't start working on this and get disappointed.

**Comment by nimanthadilz** [comment]
> @nimanthadilz How can you submit a PR without being assigned ? I requested almost 17 hours ago from now.

@baratanurag Sorry about your disappointment. Please note that in the `CONTRIBUTING.md`, under the `Contributing` Section, they never mention about the requirement of an assignment before submitting a pull request. The only requirement is the communication of the change. Therefore, I think me submitting a pull request without being assigned is not an issue. But again, I really apologize if you got disappointed.
