### ISSUE TITLE
Create the home page

### ISSUE THREAD

**Issue by Suvink** [GitHubExperts-LK/peliculopedia#7]
Code the home page and link with Firebase to fetch data. You may collaborate with the #5 and #3 contributors to get the Firebase configured.

**Comment by AhamedR** [comment]
Hey, @Suvink I can start with the designing phase Since we haven’t configured the Firebase yet.

**Comment by AhamedR** [comment]
We do not have a mobile-friendly design yet !

**Comment by Suvink** [comment]
Well it's a little complicated but we can try this.
Transform the left section into a dropdown menu, Keep the middle part as it is and again transform the right part into a horizontal scrolling section.
What do you think?

**Comment by AhamedR** [comment]
Sounds good to me, Shall we make the left section a slider for mobile?

**Comment by Suvink** [comment]
Sure! Go ahead
